# Generated by Django 2.1.2 on 2018-10-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_4', '0002_auto_20181013_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='teacher',
        ),
    ]
