# Generated by Django 2.1.2 on 2018-10-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_4', '0003_auto_20181013_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
