# Generated by Django 2.1.2 on 2018-10-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_4', '0007_teacher_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
